language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

sudo: false

-before_install:
  - apt-get -qq -y update

install:
  - add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - apt-get update
  - apt-get install -y qgis python-coverage xvfb python-nosexcover
  - pip install --upgrade pip
  - pip install --upgrade pep8
  - pip install --upgrade pylint

before_script:
  - echo "Build starting on " `date`
  - export QGIS_PREFIX_PATH=/usr
  - export PYTHONPATH=${QGIS_PREFIX_PATH}/share/qgis/python/:${QGIS_PREFIX_PATH}/share/qgis/python/plugins:`pwd`
  - echo "PYTHONPATH:" $PYTHONPATH
  - export LD_LIBRARY_PATH=${QGIS_PREFIX_PATH}/lib

script:
  - pep8 --ignore=E501 --exclude=test ./
  - make pylint
  - xvfb-run --server-args="-screen 0, 1024x768x24" nosetests -A 'not slow' -v --with-id --with-xcoverage --with-xunit --verbose --cover-package=qgis2web

notifications:
  email:
    - tom.chadwin@nnpa.org.uk
