language: generic
sudo: required
dist: trusty

virtualenv:
  system_site_packages: true

-before_install:
  - sudo apt-get -qq -y update

install:
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update
  - sudo apt-get install -y qgis xvfb
  - pip install --upgrade pip
  - sudo pip install coverage
  - sudo pip install nosexcover
  - sudo pip install --upgrade pep8
  - sudo pip install --upgrade pylint
  - sudo pip install nose-faulthandler

before_script:
  - echo "Build starting on " `date`
  - export QGIS_PREFIX_PATH=/usr
  - export PYTHONPATH=${QGIS_PREFIX_PATH}/share/qgis/python/:${QGIS_PREFIX_PATH}/share/qgis/python/plugins:`pwd`
  - echo "PYTHONPATH:" $PYTHONPATH
  - export LD_LIBRARY_PATH=${QGIS_PREFIX_PATH}/lib

script:
  - pep8 --exclude=test ./
  - make pylint
  - xvfb-run --server-args="-screen 0, 1024x768x24" nosetests -s --nologcapture -A 'not slow' -v --with-id --with-xcoverage --with-xunit --verbose --cover-package=qgis2web

notifications:
  email:
    - tom.chadwin@nnpa.org.uk
