language: python
sudo: required
dist: trusty

env:
  - QGIS_REPO=http://qgis.org/debian-ltr
  - QGIS_REPO=http://qgis.org/debian
  - QGIS_REPO=http://qgis.org/debian-nightly

virtualenv: 
  system_site_packages: true 

addons: 
  apt: 
    packages: 
      - python-software-properties 

-before_install:
  - sudo apt-get -qq -y update
  - export PATH="/home/travis/bin:/home/travis/.local/bin:/home/travis/.gimme/versions/go1.5.1.linux.amd64/bin:/home/travis/.local/bin:/usr/local/rvm/gems/ruby-2.2.3/bin:/usr/local/rvm/gems/ruby-2.2.3@global/bin:/usr/local/rvm/rubies/ruby-2.2.3/bin:/home/travis/.phpenv/shims:/usr/local/phantomjs/bin:/usr/local/phantomjs:/home/travis/perl5/perlbrew/bin:/home/travis/.nvm/versions/node/v4.1.2/bin:./node_modules/.bin:/usr/local/maven-3.1.1/bin:/usr/local/gradle/bin:/usr/local/clang-3.5.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/travis/.phpenv/bin:/usr/local/rvm/bin"

install:
  - sudo add-apt-repository ${QGIS_REPO}
  - sudo apt-get update
  - sudo apt-get install -y --force-yes qgis python-qgis
  - pip install --upgrade pip
  - pip install coverage
  - pip install nose
  - pip install --upgrade pep8
  - pip install --upgrade pylint
  - pip install python-coveralls
before_script:
  - echo "Build starting on " `date`
  - export QGIS_PREFIX_PATH=/usr
  - export PYTHONPATH=${QGIS_PREFIX_PATH}/share/qgis/python/:${QGIS_PREFIX_PATH}/share/qgis/python/plugins:`pwd`
  - echo "PYTHONPATH:" $PYTHONPATH
  - export LD_LIBRARY_PATH=${QGIS_PREFIX_PATH}/lib

script:
  - pep8 --exclude=test ./
  - make pylint
  - QGIS_DEBUG=0 xvfb-run --server-args="-screen 0, 1024x768x24" nosetests -s --nologcapture -A 'not slow' -v --with-id --with-coverage --verbose --cover-package=qgis2web --cover-package=maindialog --cover-package=utils --cover-package=configparams --cover-package=olwriter --cover-package=leafletWriter  --cover-package=olScriptStrings --cover-package=basemaps --cover-package=leafletFileScripts --cover-package=leafletLayerScripts --cover-package=leafletScriptStrings

after_success:
  - coveralls


notifications:
  email:
    - tom.chadwin@nnpa.org.uk
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5278d2ea8e892b8f3c32
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
