language: python
python:
  - "2.7"
# command to install dependencies
install: #"pip install -r requirements.txt"
	- apt-get install -y qgis 
# command to run tests
script: source scripts/run-env-linux.sh; make test
