language: generic
sudo: required
dist: trusty

virtualenv:
  system_site_packages: true

-before_install:
  - sudo apt-get -qq -y update

install:
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update
  - sudo apt-get install -y qgis xvfb
  - sudo pip install --upgrade pip
  - sudo pip install coverage
  - sudo pip install nosexcover
  - sudo pip install --upgrade pep8
  - sudo pip install --upgrade pylint

before_script:
  - echo "Build starting on " `date`
  - export QGIS_PREFIX_PATH=/usr
  - export PYTHONPATH=${QGIS_PREFIX_PATH}/share/qgis/python/:${QGIS_PREFIX_PATH}/share/qgis/python/plugins:`pwd`
  - echo "PYTHONPATH:" $PYTHONPATH
  - export LD_LIBRARY_PATH=${QGIS_PREFIX_PATH}/lib
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start


script:
  - pep8 --exclude=test ./
  - make pylint
  - nosetests -s --nologcapture -A 'not slow' -v --with-id --with-xcoverage --with-xunit --verbose --cover-package=qgis2web

notifications:
  email:
    - tom.chadwin@nnpa.org.uk
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5278d2ea8e892b8f3c32
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
